### ISSUE TITLE
version scope doesn't work - equals session scope

### ISSUE THREAD

**Issue by ghost** [jianstm/Once#1]
If I do a do.run block using version scope, the tutorial doesn't show again during the app lifetime, but if I restart the app, it'll show again.

**Comment by luoxiu** [comment]
Hi @ghubaddole , first of all, thank you for your feedback!

I've published 1.0.0, which refactored some of the code to improve ease of use and performance. Please have a try! I believe it fixes the issue of version scope. 

Very sorry to reply so late, if you have further feedback, feel free to open a new ticket. Thanks again, Once is better because of your feedback!
